# Generated by Django 6.0.8 on 2026-10-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('access_id', models.CharField(max_length=32)),
                ('merchant_id', models.CharField(blank=True, max_length=32)),
                ('token', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='brands.brand')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('brand', 'day'), name='uniq_brand_sync_day')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('txn_date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('player_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=64)),
                ('bank', models.CharField(blank=True, max_length=128)),
                ('acc_name', models.CharField(blank=True, max_length=255)),
                ('acc_no', models.CharField(blank=True, max_length=64)),
                ('bsb', models.CharField(blank=True, max_length=32)),
                ('pay_id', models.CharField(blank=True, max_length=128)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='brands.brand')),
            ],
            options={
                'indexes': [models.Index(fields=['txn_date', 'brand', 'status'], name='brands_tran_txn_dat_075f11_idx')],
                'constraints': [models.UniqueConstraint(fields=('brand', 'external_id'), name='uniq_brand_txn')],
            },
        ),
    ]
